name: Buildar e publicar imagem para o Docker Hub

on:
  push:
    branches:
      - master

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: buildar imagem
        run: |
          docker build . -t victorvsl7/anime-monitor:latest
      - name: publicar imagem no Docker
        run: |
          docker login -u victorvsl7 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push victorvsl7/anime-monitor:latest